### ISSUE TITLE
Wrong margin on Contributors page

### ISSUE THREAD

**Issue by Adalyat** [thecodejunkie/github.expandinizr#13]
There are wrong gap between different contributor's cell (see attachment)
If it's important I use Googlel Chrome ver. 33.0.1750.154 m on Windows 7 OS.
![wrong-margin](https://f.cloud.github.com/assets/3648114/2493192/13843838-b283-11e3-8551-8eb98047a040.jpg)

**Comment by khellang** [comment]
@Adalyat Are you seeing this with the latest version?
