### ISSUE TITLE
Settings page (all tabs) stretched incorrectly

### ISSUE THREAD

**Issue by Fryguy** [thecodejunkie/github.expandinizr#15]
Settings -> Options rubs up against Settings box...
Settings -> Collaborators, Webhooks, or Deploy keys are way to the right.

**Comment by khellang** [comment]
@Fryguy Are you still seeing this?

**Comment by Fryguy** [comment]
Nope..seems fixed :+1:

**Comment by khellang** [comment]
:+1:
