### ISSUE TITLE
Toolbar button and/or keyboard shortcut for toggling the extension

### ISSUE THREAD

**Issue by adamralph** [thecodejunkie/github.expandinizr#22]
I love this extension, but sometimes I want to craft what I write on GitHub to look nice for people who don't have it, e.g. when raising an issue with a code snippet I want to make sure I don't send the reader into horizontal scroll bar hell by making the code too wide.

It would be awesome to have a button in the Chrome toolbar and/or a keyboard shortcut which toggles the extension on and off, so I can quickly check how standard view users will see what I have written before submitting it.

**Comment by khellang** [comment]
@adamralph What do you think about something like this?

![expand](https://cloud.githubusercontent.com/assets/582487/7085355/585f7294-df76-11e4-8a1a-2362ae39113b.gif)

**Comment by adamralph** [comment]
All kinds of awesome.

The problem occurs when code blocks are too wide. Regular text is fine.

This would be a great addition, and would save me having to switch the whole site back to narrow when writing a comment, so :+1: to the proposal.

However, this won't catch all use cases, e.g. sometimes when browsing current source I want to know how it looks to someone with a regular width view, so I'd still also like a button which toggles the entire site width. But that shouldn't hold back adding the button you've suggested, that's also a great feature.

**Comment by adamralph** [comment]
The shrink/expand button for comments is great, :+1: to it, but it only provides a subset of the functionality which I'm proposing in this issue (see my last comment).

**Comment by khellang** [comment]
I'm not sure how easy it is to "toggle" CSS injection without reloading the page, and at that point, you might as well just disable the extension and reload yourself.

**Comment by khellang** [comment]
The way the extension works is we override _existing_ CSS styling using `!important`. Once it's injected into the site, it's not going anywhere. In order to be able to toggle classes, we'd have to define our own CSS classes which we could toggle using JavaScript - not a trivial task AFAIK. It could maybe be possible to do it using some convention, I'm not sure.

**Comment by adamralph** [comment]
Disabling the extension is an option, but it requires 3 clicks, a scroll and an another mouse click :tired_face: (perhaps there's an easier way).

I'll leave it to you guys to gauge the feasibility of implementing a full toggle since I'm a client side ignoramus. If it can't be done then it can't be done, no worries.
