### ISSUE TITLE
Split diff comments too long

### ISSUE THREAD

**Issue by neilpa** [thecodejunkie/github.expandinizr#36]
If you use split diff instead of unified comments are full width rather than half-sized to whatever split you comment on.

**Comment by neilpa** [comment]
Looks like this is only a problem if the comment is associated with new code on the right.

**Comment by khellang** [comment]
Do you have an example url?

**Comment by khellang** [comment]
Ah, found one; https://github.com/dotnet/roslyn/pull/4066/files?diff=split#r35264307

**Comment by neilpa** [comment]
Sorry about that. Meant to dig one up cause I couldn't post my original since it's a private repo.
