### ISSUE TITLE
Suggestion: Github Issue/Comment Signature

### ISSUE THREAD

**Issue by Bluscream** [thecodejunkie/github.expandinizr#38]
I would really love to have a signature function for github.

For example:

------

 [![Wurst Gitter Live Chat](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/Bluscream/Wurst-IRC?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by OmgImAlexis** [comment]
@Bluscream you do realise this is a Chrome extension and not something that Github is actually adding to the site, right?

**Comment by khellang** [comment]
Thanks for the suggestion! :+!: I don't think this is something that fits into this extension very well, though :disappointed:

**Comment by Bluscream** [comment]
Just found this issue in my timeline lmao

Is this still not a thing? xD

**Comment by thecodejunkie** [comment]
@bluscream thanks for the suggestion, but it's really not a feature that is aligned with the purpose of this extension. As such I do it see is ever being added 

Thanks

**Comment by thecodejunkie** [comment]
@bluscream thanks for the suggestion, but it's really not a feature that is aligned with the purpose of this extension. As such I do it see is ever being added 

Thanks
