### ISSUE TITLE
FileName text overflow when the width is narow

### ISSUE THREAD

**Issue by vbfox** [thecodejunkie/github.expandinizr#44]
For example on https://github.com/vbfox/ExternalAnnotationsGenerator :

![2015-10-07 09_41_17-vbfox_externalannotationsgenerator](https://cloud.githubusercontent.com/assets/131878/10332606/b9938a78-6cde-11e5-911b-e427c0fbebb1.png)

Happens when the width is `< 1400px`, I don't know if it still happens for  `>= 1400px` as I don't have any long enough file name :smile:

**Comment by khellang** [comment]
I think I have a fix for this coming up. Basically we should stay away from modifying GitHub styling when res. is lower than 1400 :smile:

**Comment by vbfox** [comment]
:tada:Yes that would be nice, I think that there might be a few nice tweaks to do when lower than 1400 but most aren't the same as for over 1400 anyway so it make sense to exclude the current tweaks.

As long additions like #39 they should still appear on `< 1400px` :smile:
