### ISSUE TITLE
Add ability to create an email from an issue or PR

### ISSUE THREAD

**Issue by Pilchie** [thecodejunkie/github.expandinizr#48]
Often I want to send someone an email about an issue or PR.  Sometimes it's the author or assignee, but not always.  It would be great if expandinizr had something like the Send To Outlook feature that TFS has.  I'm thinking of adding a "mailto:" link somewhere on the page that prepopulates an email subject with a the title of the issue, and the body with a link.  It could optionally add the author/assignee as the recipient.

As an example imagine a link on the opening an email like this:

![image](https://cloud.githubusercontent.com/assets/312835/10399404/5faa46ac-6e67-11e5-84ed-c4469d3040c3.png)

**Comment by khellang** [comment]
I guess we'll recommend using :sparkles:[stashpop.io](stashpop.io):sparkles: for this :smile:
