### ISSUE TITLE
Add possibility to use Octotree extension

### ISSUE THREAD

**Issue by jacquesbh** [thecodejunkie/github.expandinizr#49]
The [octotree extension](https://chrome.google.com/webstore/detail/octotree/bkhaagjahfmjljalopjnoealnfndnagc?hl=en-US&utm_source=chrome-ntp-launcher) displays a tree of the repository.

It's really useful.

Is that possible to do something to allow these extensions working together?

**Comment by gep13** [comment]
@thecodejunkie @khellang does this: https://github.com/buunguyen/octotree/issues/246#issuecomment-186042423 help with making these two extension play nice together? Thanks!

**Comment by khellang** [comment]
Yeah, I think that might help. We can then use that class to change our width. Thanks for following up on this, @gep13 :+1: If you (or someone else) don't get to it soon, I can have a look some time next week :smile:
