### ISSUE TITLE
Expandinizr not expandinizing :(

### ISSUE THREAD

**Issue by hmemcpy** [thecodejunkie/github.expandinizr#50]
Something changed...

![image](https://cloud.githubusercontent.com/assets/601206/11951523/246d2786-a89a-11e5-8470-7578ef9fdac8.png)

**Comment by khellang** [comment]
Yeah, noticed this the other day as well. I'll see if I can get a PR in... :smile:

**Comment by hmemcpy** [comment]
:kiss:

**Comment by khellang** [comment]
:heart:
