### ISSUE TITLE
Right panel while creating pull request with split code diff

### ISSUE THREAD

**Issue by msx2** [thecodejunkie/github.expandinizr#52]
Up to 1399px it works fine, from 1400px going up it's as on the screenshots :)

![screen shot 2016-01-04 at 10 27 12](https://cloud.githubusercontent.com/assets/1129643/12086828/d6a40f54-b2cd-11e5-8028-d854a7fad2be.png)
![screen shot 2016-01-04 at 10 30 45](https://cloud.githubusercontent.com/assets/1129643/12086880/464306d0-b2ce-11e5-9e12-5771de7e6666.png)
![screen shot 2016-01-04 at 10 30 52](https://cloud.githubusercontent.com/assets/1129643/12086881/4645427e-b2ce-11e5-9108-94c8caf53676.png)

**Comment by khellang** [comment]
Hmm. That's weird :confused: What version are you using? I'm on 1.8.0 (latest) and can't see it on any resolution. Do you have another extension eating up some space?

![image](https://cloud.githubusercontent.com/assets/582487/12087140/e28b3024-b2d0-11e5-9933-e00e9e2ee9af.png)

**Comment by msx2** [comment]
I'm using 1.8.0, and I don't have any other extension. But I just found the exact reason and step to reproduce for this behavior.

When you push your code to GitHub and want to create a new pull request, you may use this button here

![screen shot 2016-01-04 at 10 52 39](https://cloud.githubusercontent.com/assets/1129643/12087319/4c2415c2-b2d2-11e5-9741-f840f6555b68.png)

And if you have the split view of the code diff enabled, it opens as on the screenshots above. For unified view it works perfectly fine.
This is the only method I am able to reproduce this over and over again :smile:

**Comment by khellang** [comment]
Ah, yes. Split diff was it. I'll see if I can submit a fix soon :smile:
