### ISSUE TITLE
Bug: Wide mode doesn't widen graphs/"network view"

### ISSUE THREAD

**Issue by gdevenyi** [thecodejunkie/github.expandinizr#63]
![screenshot from 2016-09-21 10 27 42](https://cloud.githubusercontent.com/assets/3001850/18748406/10eada4e-80a0-11e6-9387-e003253ae2ea.png)

**Comment by khellang** [comment]
I'm not sure what we can do about that. It's rendered using a canvas, not CSS, so there's not much we can do when it comes to styling.

**Comment by khellang** [comment]
Looks like this work with the latest version (v2.0.0):

![image](https://user-images.githubusercontent.com/582487/62109989-bce94000-b2ad-11e9-9bdf-cd96ef369cbf.png)
