### ISSUE TITLE
Weird button appears on collapsed/outdated comments

### ISSUE THREAD

**Issue by hmemcpy** [thecodejunkie/github.expandinizr#64]
Doesn't happen with expandinizr disabled:

![image](https://cloud.githubusercontent.com/assets/601206/19715998/ce7a2a20-9b61-11e6-9d5d-8dcb4e35f4da.png)

**Comment by khellang** [comment]
Yeah, I think that's going away in 2.0. It's a hassle to maintain it and doesn't behave as it should.
