### ISSUE TITLE
Automatically Disable for "Projects"

### ISSUE THREAD

**Issue by sbenders-abbyy** [thecodejunkie/github.expandinizr#65]
Great Chrome extension!

In the projects tab ( example https://github.com/thecodejunkie/github.expandinizr/projects), GitHub naturally already uses the full width of the monitor, and the expandinizr's use is no longer needed.
Could you make it so the extension automatically is disabled for the GitHub Projects?

Thanks!

**Comment by khellang** [comment]
Hey @sbenders-abbyy! Is there a particular reason you want the extension disabled for projects? Aret there any issues?

**Comment by sbenders-abbyy** [comment]
Hi! Honestly, I'd have to go back and check (as this was almost a year ago and I'm not frequently using the plugin), but I think it was causing display issues (because that particular page of GitHub utilized full-width, and expandinizr was layered on top). I can't remember now, so feel free to consider this issue closed or low priority.

Thanks!

**Comment by khellang** [comment]
I don't think this is a big issue. Feel free to re-open if there's any issues.
