### ISSUE TITLE
github.expandinizr no longer plays nice with octotree

### ISSUE THREAD

**Issue by motowilliams** [thecodejunkie/github.expandinizr#67]
Seems fine when the browser isn't full screen but once you witness the firepower of this fully armed and operational ~battle station~ browser the view get's overlaid with octotree - examples shown are non-full screen vs full screen

![github-expand](https://user-images.githubusercontent.com/137777/39075419-c1cfc3f6-44b2-11e8-8976-93a73bd3315e.gif)

**Comment by khellang** [comment]
This is pretty awkward, but the "playing nice with Octotree" part has been sitting in a branch and never actually been released. It'll be part of the 2.0 release which will ship very very soon 😄

**Comment by khellang** [comment]
With the latest version (v2.0.0), it should work much better with Octotree.
