### ISSUE TITLE
No longer expanding

### ISSUE THREAD

**Issue by TylerBrinkley** [thecodejunkie/github.expandinizr#68]
I don't know if this is just me but as of today github.expandinizr is no longer expanding for me.

@thecodejunkie @khellang

**Comment by khellang** [comment]
Hmm. Yeah, I just noticed this as well. Will have to take a look. Hopefully @thecodejunkie is around to push a new release.

**Comment by khellang** [comment]
These issues seems to be fixed with the latest code in https://github.com/thecodejunkie/github.expandinizr/pull/59, which has now been merged. Just need to push it to the Chrome Store. Extension should be updated sometime today 😄

**Comment by khellang** [comment]
It would be nice if people could report back once they see the changes, so we can close this issue 😉

**Comment by khellang** [comment]
The new version should be published now. I just did an explicit update under "manage extensions" and it updated to the latest version. Everything looks like it's working again at my end, at least.

**Comment by TylerBrinkley** [comment]
It's working for me now when clicking on the icon to toggle it on but for some reason it defaults to being off when opening a new tab.

**Comment by khellang** [comment]
> for some reason it defaults to being off when opening a new tab.

Hmm. If you refresh a few times, is it always disabled? It looks like there might be some kind of race condition where it fails to add the proper class to enable the styling in some cases.

**Comment by TylerBrinkley** [comment]
Refreshing is switching it back to disabled most of the time though not always.

**Comment by khellang** [comment]
I'm getting  the folllowing in my console when it occurs:

> Uncaught TypeError: Cannot read property 'classList' of null

Looks like `document.body` is `null` in some of the event callbacks.

**Comment by TylerBrinkley** [comment]
Yes, I'm getting the same error message.

**Comment by khellang** [comment]
Looks like we'll have to do an "oh shit"-release... Would you mind pulling down [this version](https://www.dropbox.com/s/bqhubxl56hpgvw1/github.expandinizr%20v2.0.1.zip?dl=0) and take it for a spin? Just to see if it's fixed on your machine?

**Comment by TylerBrinkley** [comment]
So far so good.

**Comment by TylerBrinkley** [comment]
Thanks @khellang!

**Comment by khellang** [comment]
The patched version is now in the store, coming to a browser near you Very Soon 😊 Thanks for the help!
